version: "3.7"
services:
  fastapi:
    container_name: VisionMall_Backend
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    command: python main.py
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - DB_URL=${DB_URL}
      - SENTRY_DSN=${SENTRY_DSN}
      - GOOGLE_CLIENT_ANDROID_ID=${GOOGLE_CLIENT_ANDROID_ID}
      - GOOGLE_CLIENT_IOS_ID=${GOOGLE_CLIENT_IOS_ID}
      - GPT_API_KEY=${GPT_API_KEY}

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fastapi